spring:
  data:
    mongodb:
      uri: mongodb://root:9761216%40Chentt%40123@172.16.5.238:8117/radar?authSource=admin
      authentication-database: admin
  datasource:
    url: jdbc:mysql://172.18.3.106:3306/radar?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: cg_mall
    password: cg_mall@123
  redis:
    host: 172.18.3.153
    password: 4gTm#LXG
    timeout: 2000ms
    database: 12  #默认有16个db(集群模式用hash槽代替)，这里配置具体使用的db，默认是0

mobile:
  info:
    path: E:\workspace\radar\resources\moble_info.csv #手机号码归属地文件
ip2region:
  db:
    path: E:\workspace\radar\resources\ip2region.db #IP地址库文件
elasticsearch:
  ip: 172.18.3.67
  port: 9200
  pool-size: 5
  cluster:
    name: elasticsearch
  url: http://127.0.0.1:9200
  username: elastic # 不存在就留空
  password: $uABnAhFoc #
sys:
  conf:
    app: admin # admin 或者 engine， 根据启动的项目名称进行选择
    entity-duplicate-insert: false # 事件是否允许重复插入
    mongo-restore-days: 93 # 事件保存时间，默认3个月
    workdir: /radar/workdir #   工作目录
server:
  port: 6580
